BEGIN;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS email_verify_hash TEXT,
  ADD COLUMN IF NOT EXISTS email_verify_expires_at TIMESTAMPTZ;

COMMIT;
